[programs.localnet]
convergence_hack = "6yBt5s2MMBanRq2k9kCorgnXRjwQG5gRmboKPQ2SnjTd"

[programs.devnet]
convergence_hack = "6yBt5s2MMBanRq2k9kCorgnXRjwQG5gRmboKPQ2SnjTd"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/vladimir/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
