"""init

Revision ID: 5075c4ce71c8
Revises: 
Create Date: 2022-01-15 22:53:56.892637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5075c4ce71c8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('maker', sa.Text(), nullable=True),
    sa.Column('taker', sa.Text(), nullable=True),
    sa.Column('maker_lamports_offer', sa.NUMERIC(), nullable=True),
    sa.Column('maker_lamports_request', sa.NUMERIC(), nullable=True),
    sa.Column('maker_tokens_request', sa.JSON(), nullable=True),
    sa.Column('maker_locked_tokens', sa.JSON(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('escrow_state_pubkey', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deal')
    # ### end Alembic commands ###
